---

name: Notify Team on New Discussion
"on":
  discussion:
    types: [created]

jobs:
  notify_team:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Team
        uses: actions/github-script@v7
        with:
          script: |
            const discussion = context.payload.discussion;
            const category = discussion.category.name;

            const teams = await github.rest.teams.list({
              org: context.repo.owner,
            });

            const team = teams.data.find(t => t.name === category);

            if (team) {
              // Notify the team by mentioning the name in a comment
              const commentBody = `@${team.name} A new discussion was created in
                                    the "${category}" category: ${discussion.html_url}`;

              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: discussion.number,
                body: commentBody,
              });
            } else {
              console.log(`No team found for category: ${category}`);
            }
